import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { AlertCircle, CheckCircle } from 'lucide-react';
import * as api from '../api';

export default function ResetPassword() {
  const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password.length < 6) { setError('পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।'); return; } if (password !== confirm) { setError('পাসওয়ার্ড দুটি মিলছে না।'); return; } setLoading(true); try { await api.resetPassword(password); setSuccess(true); setTimeout(() => navigate('/dashboard'), 1500); } catch (err: any) { setError(err.message || 'রিসেট লিংকটি অবৈধ বা মেয়াদ শেষ হয়েছে। আবার রিসেট লিংক নিন।'); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-gray-50 flex items-center justify-center p-5"><div className="bg-white w-full max-w-md rounded-2xl shadow-lg p-7"><h1 className="text-2xl font-bold text-gray-800">নতুন পাসওয়ার্ড</h1><p className="text-sm text-gray-500 mt-2 mb-6">একটি শক্তিশালী নতুন পাসওয়ার্ড দিন।</p>{success ? <div className="bg-green-50 border border-green-200 text-green-700 p-4 rounded-xl text-sm flex gap-2"><CheckCircle size={18} />পাসওয়ার্ড পরিবর্তন হয়েছে। আপনাকে ড্যাশবোর্ডে নেওয়া হচ্ছে...</div> : <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-gray-700">নতুন পাসওয়ার্ড<input type="password" required value={password} onChange={e => setPassword(e.target.value)} className="mt-1.5 w-full px-3 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#006A4E]" /></label><label className="block text-sm font-medium text-gray-700">পাসওয়ার্ড নিশ্চিত করুন<input type="password" required value={confirm} onChange={e => setConfirm(e.target.value)} className="mt-1.5 w-full px-3 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#006A4E]" /></label>{error && <p className="text-sm text-red-600 flex gap-1"><AlertCircle size={16} />{error}</p>}<button disabled={loading} className="w-full py-3 rounded-xl bg-[#006A4E] text-white font-semibold disabled:opacity-60">{loading ? 'সংরক্ষণ হচ্ছে...' : 'নতুন পাসওয়ার্ড সংরক্ষণ করুন'}</button></form>}<Link to="/login" className="block text-center text-sm text-[#006A4E] mt-5 hover:underline">লগইনে ফিরে যান</Link></div></div>;
}
